version: '3.9'

services:
  # MongoDB service
  mongo_db:
    image: mongo:latest
    restart: always
    volumes:
      - mongo_db:/data/db
  
  #Nestjs API service
  inventory:
    build:
      context: .
      dockerfile: apps/inventory/Dockerfile
      target: dev
    ports:
      - 4001:4001
    volumes:
      - ./src:/app/src
    depends_on:
      - mongo_db  
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    ports:
      - 4000:4000
    volumes:
      - ./src:/app/src
    depends_on:
      - inventory
      
    
  
volumes:
  mongo_db: {}  


 
