export const getItems = async () => {
  return [
    {
      _id: '6563173cd6d85255804737e5',
      category: 'someting',
      item: 'xxxxsometing',
      option: 'someting',
      price: 12,
      cost: 10,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
    },
    {
      _id: '656319177b222f30385fcd02',
      category: 'someting',
      item: 'someting',
      option: 'someting',
      price: 12,
      cost: 10,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      __v: 0,
    },
    {
      _id: '656333061de084dd7bb4319b',
      itemCode: 'a001',
      category: 'icedCoffee',
      item: 'Americano',
      option: '160z',
      price: 50,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
  ];
};
