export const getItems = async () => {
  return [
    {
      _id: '6563173cd6d85255804737e51',
      category: 'frappe',
      item: 'xxxxsometing',
      option: 'someting',
      price: 12,
      cost: 10,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
    },
    {
      _id: '656319177b222f30385fcd022',
      category: 'frappe',
      item: 'someting',
      option: 'someting',
      price: 12,
      cost: 10,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      __v: 0,
    },
    {
      _id: '656333061de084dd7bb4319b3',
      itemCode: 'a001',
      category: 'iced',
      item: 'Americano',
      option: '160z',
      price: 50,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587bcc43a375d5952f7c9ce4',
      itemCode: 'a001',
      category: 'hot',
      item: 'Americano',
      option: '120z',
      price: 60,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587bce23a375d5952f7c9d05',
      itemCode: 'a001',
      category: 'hot',
      item: 'Spanish Latte',
      option: '120z',
      price: 120,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587bdba3a375d5952f7c9d36',
      itemCode: 'a001',
      category: 'iced',
      item: 'Iced Spanish Latte',
      option: '160z',
      price: 60,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587bdcb3a375d5952f7c9d57',
      itemCode: 'a001',
      category: 'iced',
      item: 'Iced Vanilla Latte',
      option: '160z',
      price: 60,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587be013a375d5952f7c9d8',
      itemCode: 'a001',
      category: 'iced',
      item: 'Iced Caramel Macchiato',
      option: '160z',
      price: 70,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587be013a375d5952f7c9d821',
      itemCode: 'a001',
      category: 'iced',
      item: 'Iced Cappuccino',
      option: '160z',
      price: 70,
      cost: 40,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
    {
      _id: '6587be013a375d5952f7c9d822',
      itemCode: 'a001',
      category: 'iced',
      item: 'Iced Cappuccino',
      option: '220z',
      price: 110,
      cost: 50,
      modifier: 5,
      onlineStoreAvailability: true,
      onlineStoreDescription: 'some description',
      VATExempt: true,
      linkInventory: ['aaa', 'bbbb', 'ccc'],
      __v: 0,
    },
  ];
};
